<?php if (!defined('ABSPATH')) die('Direct access forbidden.');
/**
 * dynamic css, generated by customizer options
 */

// if ( defined( 'FW' ) ) {
//     $primary_color = appbuff_option( 'primary_color' );
//     $custom_css	 = appbuff_option( 'custom_css' );
//     $output		 = 
//         $custom_css."
//         .test{
//             background-color: $secondary_color;
//         }";

//     wp_add_inline_style( 'appbuff-style', $output );
// }


